services:
  db:
    image: postgres:15
    container_name: sghss-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sghss
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: